#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

echo -e "⏳ Loading context data in \033[1mNGSI-LD\033[0m format"
echo -e "    - all entity data models are defined referencing the" 
echo -e "      \033[1m"${TUTORIAL_DATA_MODELS_CONTEXT}"\033[0m JSON-LD context"

#
# Create four Store Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST 'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entityOperations/upsert' \
-H 'Content-Type: application/json' \
-H 'Link: <'"${TUTORIAL_DATA_MODELS_CONTEXT}"'>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json' \
--data-raw '[
  {
    "id": "urn:ngsi-ld:Building:farm001",
    "type": "Building",
    "category": {"type": "Property", "value": ["farm"]},
    "address": {
        "type": "Property",
        "value": { "streetAddress": "Großer Stern 1", "addressRegion": "Berlin", "addressLocality": "Tiergarten", "postalCode": "10557"},
        "verified": { "type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": { "type": "Point", "coordinates": [13.3505, 52.5144]}
    },
    "name": {"type": "Property","value": "Victory Farm"},
    "owner": {"type": "Relationship", "object": "urn:ngsi-ld:Person:person001"}
  },
  {
    "id": "urn:ngsi-ld:Building:barn002",
    "type": "Building",
    "category": {"type": "Property", "value": ["barn"]},
    "address": {
        "type": "Property",
        "value": { "streetAddress": "Straße des 17. Juni", "addressRegion": "Berlin", "addressLocality": "Tiergarten", "postalCode": "10557"},
        "verified": { "type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": { "type": "Point", "coordinates": [13.3698, 52.5163]}
    },
    "name": {"type": "Property","value": "Big Red Barn"},
    "owner": {"type": "Relationship", "object": "urn:ngsi-ld:Person:person001"}
  },
  {
    "id": "urn:ngsi-ld:Building:tower003",
    "type": "Building",
    "category": {"type": "Property", "value": ["water_tower"]},
    "address": {
        "type": "Property",
        "value": { "streetAddress": "John-Foster-Dulles-Allee", "addressRegion": "Berlin", "addressLocality": "Tiergarten", "postalCode": "10557"},
        "verified": { "type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": { "type": "Point", "coordinates": [13.3598, 52.5165]}
    },
    "name": {"type": "Property","value": "Triton Tower"},
    "owner": {"type": "Relationship", "object": "urn:ngsi-ld:Person:person001"}
  },
  {
    "id": "urn:ngsi-ld:Building:farm002",
    "type": "Building",
    "category": {"type": "Property", "value": ["farm"]},
    "address": {
        "type": "Property",
        "value": { "streetAddress": "Hardenbergplatz 8", "addressRegion": "Berlin", "addressLocality": "Tiergarten", "postalCode": "10787"},
        "verified": { "type": "Property", "value": true}
    },
    "location": {
        "type": "GeoProperty",
        "value": { "type": "Point", "coordinates": [13.3127, 52.4893]}
    },
    "name": {"type": "Property","value": "Animal Farm"},
    "owner": {"type": "Relationship", "object": "urn:ngsi-ld:Person:person002"}
  },
  {
    "id": "urn:ngsi-ld:Person:person001",
    "type": "Person",
    "name": {"type": "Property","value": "Old MacDonald"}
  },
  {
    "id": "urn:ngsi-ld:Person:person002",
    "type": "Person",
    "name": {"type": "Property","value": "Napoleon the Pig"}
  }
]'

echo -e " \033[1;32mdone\033[0m"
