#!/bin/bash
#
#  Command Line Interface to start all services associated with the Tutorial
#

set -e

echo -e "Checkout the \033[1;36mNGSI-v2\033[0m branch of this repository to run the Smart Supermarket tutorial.\n"
# echo -e "Checkout the \033[1;31mNGSI-LD\033[0m branch of this repository to run the Smart Farm tutorial.\n"
